### ISSUE TITLE
您好，请教个问题。我用您这个脚本生成0-9数据集训练crnn

### ISSUE THREAD

**Issue by huoo2015** [wulivicte/synthdata-zh#1]
生成数据集后，训练发现 , accuray: 0.097222 一直接近0.看到preds的内容，都是同一个值
您知道是什么原因导致的？
4------------------------- => 4                   , gt: 3
4------------------------- => 4                   , gt: 5
4------------------------- => 4                   , gt: 1
4------------------------- => 4                   , gt: 9
4------------------------- => 4                   , gt: 0
4------------------------- => 4                   , gt: 3
4------------------------- => 4                   , gt: 1
4------------------------- => 4                   , gt: 6
4------------------------- => 4                   , gt: 8

**Comment by YoungMiao** [comment]
@huoo2015 你好，你查看生成的图片样例是否是不同的数？
